name: mc_reaper_sound
description: Creating reaper projects for minecraft sounds.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # dart stuff
  collection: ^1.16.0
  logger: ^1.1.0
  uuid: ^3.0.6

  #navigation
  go_router: ^3.0.1

  # state management
  provider: ^6.0.2
  shared_preferences: ^2.0.13

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

